import type { Metadata } from "next";
import { dir } from "i18next";

import { languages } from "../i18n/settings";

import { Header } from "../sections/Header";

import { montserrat } from "@/utils/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "TehRemont",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

interface Props {
  children: React.ReactNode;
  params: { lng: string };
}

export default function RootLayout({ children, params: { lng } }: Props) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <head />
      <body className={`${montserrat.className}`}>
        <Header lng={lng} />
        {children}
      </body>
    </html>
  );
}
